# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Barcelona Cyber Security Community
email: info@cyber.barcelona
description: Barcelona Cyber Security Community
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: 
github_url: https://github.com/bcncybersecurity/
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/company/cyber-barcelona/
pinterest_url: 
slack_url: https://cyberbcn.slack.com/
twitter_url: https://twitter.com/bcncybersec

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: bcncybersec
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
